pipeline {
    agent any 
    stages {
        stage('Compile and Clean') { 
            steps {

                sh "mvn clean compile"
            }
        }
       

        stage('deploy') { 
            steps {
                sh "mvn package"
            }
        }


        stage('Build Docker image'){
            steps {
              
                sh 'docker build -t  pratikchougulelti/imagename:latest .'
            }
        }

        stage('Docker Login'){
            
            steps {
                 withCredentials([string(credentialsId: 'pratikchougulelti', variable: 'ce965861-7775-419d-80a9-5bf0fb45bf23')]) {
                    sh "docker login -u pratikchougulelti -p ${ce965861-7775-419d-80a9-5bf0fb45bf23}"
                }
            }                
        }

        stage('Docker Push'){
            steps {
                sh 'docker push pratikchougulelti/CustomerProducerServiceApplication:latest'
            }
        }
        
        stage('Docker deploy'){
            steps {
               
                sh 'docker run -itd -p  8099:8099 pratikchougulelti/CustomerProducerServiceApplication:latest'
            }
        }

        
        stage('Archving') { 
            steps {
                 archiveArtifacts '**/target/*.jar'
            }
        }
    }
}

